/**
 * Unified A2A seller agent entrypoint: ONE file for BOTH hosted deploy runtimes.
 * Generated by `bag recipe code agent`.
 *
 * This is the VALUABLE agent AND the SOLE key-holder/signer. The same
 * process satisfies both hosted-agent container contracts at once:
 *
 * - hosted provider mode `--provider aws`: `@a2a-js/sdk` express app,
 *   agent card at `/.well-known/agent-card.json` + JSON-RPC `message/send`,
 *   plus `GET /ping` for that runtime's liveness contract (contract port
 *   9000).
 * - the second hosted provider mode (the runtime's own docs name its
 *   `--provider` value): pass-through `POST /invocations` + `POST /responses`
 *   (that runtime's Responses protocol for managed incoming A2A) plus
 *   `GET /readiness` (contract port 8088).
 *
 * The server listens on BOTH contract ports (9000 and 8088; `AGENT_PORT`
 * prepends a local override), so the SAME image deploys to either cloud with
 * zero source changes: the per-cloud build only pins the CPU arch.
 *
 * A2A skills (executor.ts, shared by every carrier):
 *
 *     negotiate     → read the FIXED list price → CLAMP to [min,max] → EIP-191 SIGN
 *                     the offer (no LLM, no tools) → return the signed offer (or reject)
 *     notify_funded → re-verify the funded job on-chain (fast) → ACK accepted at once,
 *                     then in the BACKGROUND: deterministic strategy work
 *                     (vendor/strategies, no model) → manifest → storage →
 *                     submitResult (SIGN + broadcast). The buyer polls the chain for
 *                     the deliverable. Each notify also sweeps other FUNDED jobs
 *                     (buyer-push fallback). While background work is in flight the
 *                     `/ping` handler reports HEALTHY_BUSY so AgentCore keeps the
 *                     scale-to-zero runtime warm until it lands.
 *
 * On Foundry the skills ride as a JSON text envelope (`{"skill": ...}`)
 * because Foundry's incoming A2A is text-modality only, {@link SkillRouter}
 * parses it and dispatches through the SAME `SellerAgentExecutor.dispatch`.
 *
 * ## How x402 buyers reach /x402 on either runtime
 *
 * Neither hosted-agent gateway allows anonymous ingress, and both strip or
 * gate the buyer's half of the HTTP exchange, so the anonymous buyer talks
 * to an external gateway that wraps each request in `http-envelope-v1`
 * (outer HTTP always 200) and forwards it with the runtime's own auth.
 * {@link createEnvelopeMiddleware} unwraps the tunnel onto the in-process
 * {@link X402Seller} below. See the runtime's self-hosted x402 gateway
 * guide for each provider mode.
 *
 * Secrets: in the aws provider mode, `loadRuntimeSecrets()` pulls the secrets
 * bundle named by BNBAGENT_RUNTIME_SECRET_ID; in the second provider mode the
 * platform's managed connection injects the same variables before the
 * process starts (the loader no-ops when the pointer is absent).
 *
 * ## Boundaries (do NOT cross: they are the whole point)
 *
 * - The agent does ALL deterministic SIGNING (quote-sign + submit + settle).
 *   ALL signing is FIXED code in `signing.ts`, never callable by any model
 *   or tool.
 * - The price is a FIXED list price from studio.toml, clamped to
 *   [min_price, max_price] before signing; no request field reaches it.
 * - The deliverable is computed by the deterministic strategy core in
 *   `vendor/strategies` (see `buildRunWork`): same inputs, same output, no
 *   model call anywhere in the delivery path. `model.ts` and `tools.ts` are
 *   scaffold modules this entrypoint does not import.
 * - `settle` (claim payment after the dispute window) is operator-driven:
 *   run `bag erc8183 settle <job_id>`; it is deliberately NOT an A2A skill.
 */

import { makeRunWork } from "../vendor/strategies/dispatch.js";
import { randomUUID } from "node:crypto";
import { pathToFileURL } from "node:url";
import {
  GetSecretValueCommand,
  SecretsManagerClient,
} from "@aws-sdk/client-secrets-manager";
import { DefaultRequestHandler, InMemoryTaskStore } from "@a2a-js/sdk/server";
import {
  agentCardHandler,
  jsonRpcHandler,
  UserBuilder,
} from "@a2a-js/sdk/server/express";
import {
  loadStudioToml,
  type TomlTable,
} from "@bnbagent/studio-runtime/config";
import {
  ensureAltanaSessionLoaded,
  ensureKeystoreMaterialized,
  ensureTwakMaterialized,
  getWallet,
} from "@bnbagent/studio-runtime/wallet";
import {
  createEnvelopeMiddleware,
  X402_SELL_PATH,
  type X402HttpRequest,
  type X402RunWork,
  X402Seller,
} from "@bnbagent/studio-runtime/x402";
import express from "express";
import { buildAgentCard, publicBaseUrl } from "./agentCard.js";
import { SellerAgentExecutor } from "./executor.js";
import type { RunWork } from "./sellerCore.js";

/**
 * fix 2026-09-03 H277: ONE request-body limit for both parsers, derived from the front
 * end rather than guessed. The reverse proxy caps proxied requests at 64k, so the old
 * 8mb JSON limit was reachable only from this host and let a loopback caller push 8 MB
 * into a 512 MB service. 1mb is the number the x402 text parser already ran with in
 * production and still leaves 16x headroom over the proxy cap. AGENT_MAX_BODY (for
 * example "8mb") restores a larger limit for a direct caller that needs one.
 */
function maxBody(): string {
  return process.env.AGENT_MAX_BODY || "1mb";
}

const APP_NAME = "agent";

/**
 * Deliverable `generator` label: this seller's own name, read from
 * studio.toml `[project].name` (minus the `-agent` suffix) so each delivered
 * manifest is self-identifying. Best-effort, falls back to `APP_NAME` if
 * the config can't be read.
 */
function generatorTag(): string {
  let name = "";
  try {
    const cfg = loadStudioToml();
    name = String(((cfg.project ?? {}) as Record<string, unknown>).name ?? "");
  } catch {
    // a metadata label must never break delivery
    return APP_NAME;
  }
  return name.endsWith("-agent")
    ? name.slice(0, -"-agent".length)
    : name || APP_NAME;
}

// ── Runtime secrets ───────────────────────────────────────────────────────────
// Keep plaintext secrets OUT of agentcore.json. When BNBAGENT_RUNTIME_SECRET_ID
// is set (deployed AgentCore runtime), pull a JSON {ENV_NAME: value} blob from
// the managed secrets store into the process env BEFORE anything reads it (keystore
// unlock, provider key, Cognito OAuth env). No-op locally (where
// .env.local already populated the environment) and in the second provider mode (where
// the CustomKeys connection injects the variables before the process starts).
// In a deployed AgentCore runtime the managed secret bundle is authoritative
// and replaces any stale spec-level value left by an earlier runtime revision.
async function loadRuntimeSecrets(): Promise<void> {
  const secretId = process.env.BNBAGENT_RUNTIME_SECRET_ID;
  if (!secretId) {
    return;
  }
  const resp = await new SecretsManagerClient({}).send(
    new GetSecretValueCommand({ SecretId: secretId }),
  );
  const bundle = JSON.parse(resp.SecretString ?? "{}") as Record<
    string,
    unknown
  >;
  for (const [key, value] of Object.entries(bundle)) {
    process.env[key] = String(value);
  }
}

/** studio.toml `[network].default` (best-effort; used by the funded sweep). */
function defaultNetwork(): string {
  try {
    const cfg = loadStudioToml();
    return String(
      ((cfg.network ?? {}) as Record<string, unknown>).default ?? "bsc-testnet",
    );
  } catch {
    return "bsc-testnet";
  }
}

// ── Work hook (the executor's delivery step) ─────────────────────────────────
// fix 2026-09-02 H21: this block used to describe a model-in-the-loop design
// that the function below does not run. Deterministic work core: the
// deliverable is computed by fixed strategy math in vendor/strategies
// (makeRunWork), keyed by this agent's category. Same inputs, same output,
// no model in the loop. The work runs only in an authorized value step:
// verified ERC-8183 delivery, or x402 work after its payment/free gate.
// `negotiate` is rule-based. Signing / settle are fixed code in signing.ts,
// triggered by the A2A skills only.
export function buildRunWork(): RunWork {
  // DETERMINISTIC WORK CORE: deliverables are computed by fixed strategy
  // math (vendor/strategies): same inputs, same output, no model in the
  // loop. Signing stays in signing.ts, untouched.
  const work = makeRunWork("yield");
  return async (prompt) => work(prompt);
}

function hasErc8183Rail(cfg: TomlTable): boolean {
  const payments = asTable(cfg.payments);
  return asTable(payments?.erc8183) !== null;
}

function asTable(value: unknown): TomlTable | null {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as TomlTable)
    : null;
}

function flatHeaders(
  headers: Record<string, string | string[] | undefined>,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, value] of Object.entries(headers)) {
    if (typeof value === "string") out[name] = value;
    else if (value !== undefined) out[name] = value[0] ?? "";
  }
  return out;
}

function flatQuery(query: Record<string, unknown>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, value] of Object.entries(query)) {
    if (typeof value === "string") out[name] = value;
    // fix 2026-09-03 H169: express parses `?a=1&a=2` to an array, and this dropped the
    // parameter entirely while flatHeaders two functions above took value[0] for the
    // same shape. Same shape, same handling: first value wins, and a missing one
    // flattens to "" exactly as it does for headers.
    else if (Array.isArray(value)) out[name] = String(value[0] ?? "");
  }
  return out;
}

function x402Work(runWork: RunWork): X402RunWork {
  return ({ prompt }) => runWork(prompt, { sessionId: "x402" });
}

// ── Foundry text-carrier adapters ────────────────────────────────────────────

/**
 * The skill-router shim routing Foundry invocations to seller skills.
 *
 * Foundry's pass-through host receives a JSON body whose `input` is the
 * serialized skill envelope. We parse that text and dispatch it
 * DETERMINISTICALLY through `SellerAgentExecutor.dispatch` (signing.ts fixed
 * code; LLM only inside the notify_funded background work). The result is
 * serialised back to text. A non-envelope message returns the same "unknown
 * skill" reply the @a2a-js path gives: there is no free-form chat skill.
 */
export class SkillRouter {
  readonly name: string;
  readonly description =
    "ERC-8183 seller agent (negotiate + notify_funded) over A2A.";
  private readonly executor: SellerAgentExecutor;

  constructor(executor: SellerAgentExecutor, opts: { name?: string } = {}) {
    this.executor = executor;
    this.name = opts.name ?? "seller_agent";
  }

  /** Route one inbound text turn to the seller skills; returns JSON text. */
  async run(text: string | null | undefined): Promise<string> {
    const envelope = extractEnvelope(text);
    const result =
      envelope === null
        ? {
            error:
              'expected a JSON skill envelope, e.g. {"skill": "negotiate", ...}',
            skills: ["negotiate", "notify_funded"],
          }
        : await this.executor.dispatch(envelope);
    return JSON.stringify(result);
  }
}

/**
 * Parse inbound user text into a `{"skill": ...}` dict, or null.
 *
 * Foundry's incoming A2A is text-modality only, so the buyer sends the skill
 * envelope as a JSON string. Non-JSON / non-object text → null (the caller
 * replies with a deterministic "unknown skill").
 */
export function extractEnvelope(
  text: string | null | undefined,
): Record<string, unknown> | null {
  if (!text) {
    return null;
  }
  let obj: unknown;
  try {
    obj = JSON.parse(text);
  } catch {
    return null;
  }
  return obj !== null && typeof obj === "object" && !Array.isArray(obj)
    ? (obj as Record<string, unknown>)
    : null;
}

/** Extract the latest text turn from a Foundry Responses request. Foundry's
 * incoming A2A adapter is text-only and projects the caller message here. */
export function responsesInputText(input: unknown): string | null {
  if (typeof input === "string") {
    return input;
  }
  if (!Array.isArray(input)) {
    return null;
  }
  const texts: string[] = [];
  for (const item of input) {
    if (typeof item === "string") {
      texts.push(item);
      continue;
    }
    if (!item || typeof item !== "object") {
      continue;
    }
    const content = (item as Record<string, unknown>).content;
    if (typeof content === "string") {
      texts.push(content);
      continue;
    }
    if (!Array.isArray(content)) {
      continue;
    }
    for (const part of content) {
      if (part && typeof part === "object") {
        const text = (part as Record<string, unknown>).text;
        if (typeof text === "string") texts.push(text);
      }
    }
  }
  return texts.at(-1) ?? null;
}

function responseId(prefix: string): string {
  return `${prefix}_${randomUUID().replaceAll("-", "")}`;
}

function responseEnvelope(text: string, model: string) {
  const responseIdValue = responseId("resp");
  const messageId = responseId("msg");
  const part = { type: "output_text", annotations: [], logprobs: [], text };
  const item = {
    id: messageId,
    type: "message",
    status: "completed",
    role: "assistant",
    content: [part],
  };
  return {
    id: responseIdValue,
    object: "response",
    created_at: Math.floor(Date.now() / 1000),
    status: "completed",
    error: null,
    incomplete_details: null,
    instructions: null,
    max_output_tokens: null,
    model,
    output: [item],
    output_text: text,
    parallel_tool_calls: true,
    previous_response_id: null,
    reasoning: { effort: null, summary: null },
    store: true,
    temperature: 1,
    text: { format: { type: "text" } },
    tool_choice: "auto",
    tools: [],
    top_p: 1,
    truncation: "disabled",
    usage: {
      input_tokens: 0,
      input_tokens_details: { cached_tokens: 0 },
      output_tokens: 0,
      output_tokens_details: { reasoning_tokens: 0 },
      total_tokens: 0,
    },
    metadata: {},
  };
}

function sendStreamingResponse(
  res: express.Response,
  response: ReturnType<typeof responseEnvelope>,
): void {
  const item = response.output[0];
  const part = item.content[0];
  const events = [
    { type: "response.created", sequence_number: 0, response: { ...response, status: "in_progress", output: [] } },
    { type: "response.output_item.added", sequence_number: 1, output_index: 0, item: { ...item, status: "in_progress", content: [] } },
    { type: "response.content_part.added", sequence_number: 2, output_index: 0, item_id: item.id, content_index: 0, part: { ...part, text: "" } },
    { type: "response.output_text.delta", sequence_number: 3, output_index: 0, item_id: item.id, content_index: 0, delta: part.text },
    { type: "response.output_text.done", sequence_number: 4, output_index: 0, item_id: item.id, content_index: 0, text: part.text },
    { type: "response.content_part.done", sequence_number: 5, output_index: 0, item_id: item.id, content_index: 0, part },
    { type: "response.output_item.done", sequence_number: 6, output_index: 0, item },
    { type: "response.completed", sequence_number: 7, response },
  ];
  res.status(200);
  res.setHeader("content-type", "text/event-stream");
  res.setHeader("cache-control", "no-cache");
  for (const event of events) {
    res.write(`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`);
  }
  res.end("data: [DONE]\n\n");
}

// ── serving ───────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  await loadRuntimeSecrets();

  // Wallet material is NEVER bundled into the deploy artifact. `bag deploy`
  // injects it via the runtime secret channel (Secrets Manager bundle on
  // AgentCore, CustomKeys env on Foundry) and these calls (run once at cold
  // start, before any signing) materialize it on disk. Each is a no-op for
  // the other wallet kind and locally, where the wallet already lives on
  // disk:
  //  - evm-local: WALLET_KEYSTORE_JSON → keystore file (unlocked with WALLET_PASSWORD)
  //  - twak:      TWAK_WALLET_JSON / TWAK_CREDENTIALS_JSON → $TMPDIR/twak-home/.twak
  //               (exported as TWAK_HOME_DIR; twak reads TWAK_WALLET_PASSWORD itself)
  ensureKeystoreMaterialized();
  ensureTwakMaterialized();
  await ensureAltanaSessionLoaded();

  const cfg = loadStudioToml();
  const rails = { erc8183: hasErc8183Rail(cfg) };
  // fix 2026-09-02 H22: bind loopback by default. The JSON-RPC handler below
  // authenticates nobody, so a bare `pnpm dev` used to expose a live signer on
  // every interface. Set AGENT_BIND_HOST=0.0.0.0 explicitly to bind wider (a
  // container runtime that must be reached from outside needs it).
  const host = process.env.AGENT_BIND_HOST || "127.0.0.1";
  // Both hosted-agent contract ports are always bound (AgentCore A2A: 9000,
  // Foundry invocations: 8088) so one image serves either cloud. AGENT_PORT
  // (or PORT) prepends a primary override for local runs; the primary port
  // must bind (fatal), the remaining contract ports are best-effort.
  const override = Number(process.env.AGENT_PORT || process.env.PORT || "");
  // fix 2026-09-03 H276: 9000 and 8088 are fixed host-wide numbers, so on a box that
  // runs several sellers they go to whichever one booted first and the loser only ever
  // logged "unavailable" without saying what that means. The binds stay on by default
  // (one image still serves either cloud); AGENT_CONTRACT_PORTS=0 drops them for a host
  // that runs more than one seller and reaches each on its own AGENT_PORT.
  const contractPorts = process.env.AGENT_CONTRACT_PORTS !== "0";
  const ports = [
    ...new Set([
      ...(Number.isInteger(override) && override > 0 ? [override] : []),
      ...(contractPorts ? [9000, 8088] : []),
    ]),
  ];
  const port = ports[0] as number;
  const runWork = buildRunWork();

  // The executor backs the seller skills with signing.ts fixed code (NEVER an
  // LLM tool). The SAME executor serves every carrier: @a2a-js JSON-RPC,
  // Foundry invocations (SkillRouter), and Foundry Responses.
  const executor = new SellerAgentExecutor({
    runWork,
    generator: generatorTag(),
    network: defaultNetwork(),
    commerceSkills: rails.erc8183,
  });
  const agentCard = buildAgentCard({ commerceSkills: rails.erc8183 });
  const seller = await X402Seller.create({
    cfg,
    runWork: x402Work(runWork),
    walletAddress: getWallet().address,
    // The 402 challenge's resource URL must be the BUYER-facing address.
    // fix 2026-09-02 H117: resolved by publicBaseUrl() in agentCard.ts (the
    // same order the card uses: AGENTCORE_RUNTIME_URL, BNBAGENT_PUBLIC_URL,
    // the legacy AGENT_PUBLIC_URL, then the base of ERC8183_AGENT_URL); the
    // localhost fallback only suits local runs.
    resourceUrl: `${publicBaseUrl().replace(/\/$/, "")}${X402_SELL_PATH}`,
  });
  const router = new SkillRouter(executor, { name: generatorTag() });

  const handler = new DefaultRequestHandler(
    agentCard,
    new InMemoryTaskStore(),
    executor,
  );

  const app = express();

  // GET /ping status fed to AgentCore: HEALTHY_BUSY while a background
  // delivery is in flight, else HEALTHY.
  //
  // notify_funded acks immediately and runs the slow work (strategy math +
  // on-chain submit) in the background. Reporting HEALTHY_BUSY tells AgentCore the
  // runtime is still working, so the scale-to-zero runtime is NOT reaped on
  // idle before delivery lands (bounded by the session max-lifetime; ≤8h).
  app.get("/ping", (_req, res) => {
    res.json({ status: executor.isBusy() ? "HEALTHY_BUSY" : "HEALTHY" });
  });
  // Required Foundry Hosted Agent health contract. The platform will not
  // create a session or forward invocations until this returns HTTP 200.
  app.get("/readiness", (_req, res) => {
    res.json({ status: "READY" });
  });

  if (seller.state !== "disabled") {
    app.all(
      X402_SELL_PATH,
      express.text({ type: "*/*", limit: maxBody() }),
      async (req, res) => {
        const request: X402HttpRequest = {
          method: req.method,
          path: req.path,
          query: flatQuery(req.query),
          headers: flatHeaders(req.headers),
          body:
            typeof req.body === "string"
              ? req.body
              : JSON.stringify(req.body ?? ""),
        };
        const out = await seller.handle(request);
        res.status(out.status).set(out.headers).send(out.body);
      },
    );
  }

  app.use(express.json({ limit: maxBody() }));
  app.use(createEnvelopeMiddleware({ port }));

  // Foundry Invocations is a pass-through JSON contract. bnbagent-deploy's
  // positional invoke helper normalizes text to {"input":"..."}; advanced
  // callers may send the same shape directly.
  app.post("/invocations", async (req, res) => {
    const input = (req.body ?? {}) as Record<string, unknown>;
    const text = typeof input.input === "string" ? input.input : null;
    res.json({ output: await router.run(text) });
  });
  // The managed platform selects Foundry's Responses protocol so the agent
  // can be exposed through incoming A2A. Keep this adapter small and
  // deterministic: Foundry converts A2A text to Responses input, and the
  // seller result becomes one assistant output_text item.
  app.post("/responses", async (req, res) => {
    const input = (req.body ?? {}) as Record<string, unknown>;
    const output = await router.run(responsesInputText(input.input));
    const response = responseEnvelope(
      output,
      typeof input.model === "string" ? input.model : APP_NAME,
    );
    if (input.stream === true) {
      sendStreamingResponse(res, response);
    } else {
      res.json(response);
    }
  });

  app.use(
    "/.well-known/agent-card.json",
    agentCardHandler({ agentCardProvider: handler }),
  );
  // fix 2026-09-03 H168: this is the one line that makes the seller public, and it is
  // deliberate. `noAuthentication` is the intended public-seller posture: negotiate and
  // notify_funded are meant to be callable by any buyer, and the money gate is on chain
  // (a quote is only worth signing, and work is only done, once the job is FUNDED to
  // this provider). It is also what makes the unauthenticated negotiate oracle (H163)
  // and the unauthenticated notify path reachable, which is why those two are bounded
  // where they are: chain-bound and TTL-expiring quotes, and a single-flight sweep.
  // `/ping` and `/readiness` above are open for the same reason. If this ever needs to
  // change, change it here, not in the skills.
  app.use(
    jsonRpcHandler({
      requestHandler: handler,
      userBuilder: UserBuilder.noAuthentication,
    }),
  );

  // Bind every port: the primary (first) port is fatal on failure; the
  // remaining contract ports are best-effort so a local run does not die
  // when the other cloud's contract port happens to be taken.
  const servers = ports.map((p, i) => {
    const server = app.listen(p, host, () => {
      console.log(
        `[seller-agent] serving on ${host}:${p}${i === 0 ? "" : " (secondary contract port)"} (x402: ${seller.state})`,
      );
    });
    if (i > 0) {
      server.on("error", (e) => {
        // fix 2026-09-03 H276: say what losing the race means. The port is held by
        // another process on this host, so anything addressed to it reaches that
        // process and not this seller.
        console.warn(
          `[seller-agent] contract port ${p} is held by another process on this host: requests to it reach that process, not ${generatorTag()}. This seller is reachable on ${host}:${port} (${(e as Error).message})`,
        );
      });
    }
    return server;
  });
  process.once("SIGTERM", () => {
    // fix 2026-09-03 H23: server.close() drains in-flight requests but does not touch
    // an IDLE keep-alive socket, and both the x402 gateway and any A2A client hold one.
    // One idle socket kept the close callback pending forever, so the process never
    // exited on its own and the platform escalated to SIGKILL, killing a background
    // delivery mid-flight on every redeploy. Close idle sockets first, then keep a
    // deadline as a backstop. The background job is idempotent (the sweep re-delivers),
    // so nothing is lost on chain either way; what this buys is a clean exit.
    // AGENT_SHUTDOWN_GRACE_SECONDS=0 restores the wait-forever behaviour.
    let open = servers.length;
    let done = false;
    const finish = (code: number) => {
      if (done) return;
      done = true;
      process.exit(code);
    };
    for (const server of servers) {
      server.closeIdleConnections?.();
      server.close(() => {
        open -= 1;
        if (open === 0) finish(0);
      });
    }
    const grace = Number(process.env.AGENT_SHUTDOWN_GRACE_SECONDS ?? 20);
    if (grace > 0) {
      setTimeout(() => {
        console.warn(
          `[seller-agent] ${open} listener(s) still open ${grace}s after SIGTERM; exiting anyway`,
        );
        finish(0);
      }, grace * 1000).unref();
    }
  });
}

// Run only as an entrypoint (`node unifiedMain.js` / the hosted runtime),
// never on import: tests import the builders above without starting a
// server.
const isMain =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  main().catch((e) => {
    console.error("[seller-agent] fatal:", e);
    process.exit(1);
  });
}
